ALTER TABLE TB_DECLARACAO 
DROP COLUMN DT_DATA_LETIVO_FIM;
ALTER TABLE TB_DECLARACAO 
DROP COLUMN DT_LETIVO_INICIO;
ALTER TABLE TB_DECLARACAO 
DROP COLUMN DATANASCIMENTO;
ALTER TABLE TB_DECLARACAO 
DROP COLUMN DS_MATRICULA;
ALTER TABLE TB_DECLARACAO 
DROP COLUMN CD_INEP_EMEC;
ALTER TABLE TB_DECLARACAO 
DROP COLUMN NR_PERIODO_SERIE_GRAU;
ALTER TABLE TB_DECLARACAO 
DROP COLUMN NM_RESPONSAVEL;

ALTER TABLE TB_EXTENSAO_ACESSO 
ADD (DS_NOME VARCHAR2(255) );

ALTER TABLE TB_FREQUENCIA 
DROP COLUMN DT_NASCIMENTO;
ALTER TABLE TB_FREQUENCIA 
DROP COLUMN CD_INEP_EMEC;
ALTER TABLE TB_FREQUENCIA 
DROP COLUMN DS_MATRICULA;
ALTER TABLE TB_FREQUENCIA 
DROP COLUMN NM_RESPONSAVEL;

ALTER TABLE TB_INSTITUICAO_CURSO 
ADD (ST_TRANSF_SITPASS NUMBER(10) );

ALTER TABLE TB_INSTITUICAO_ENSINO 
DROP CONSTRAINT FK1NHPFXB21S43R4ODQM5QSJGBS;
ALTER TABLE TB_INSTITUICAO_ENSINO 
DROP COLUMN ID_REPRESENTANTE;
ALTER TABLE TB_INSTITUICAO_ENSINO 
ADD (ST_TRANSF_SITPASS NUMBER(10) );

ALTER TABLE TB_REPRESENTANTE_INSTITUICAO 
ADD (ST_ATIVO NUMBER(10) );
ALTER TABLE TB_REPRESENTANTE_INSTITUICAO 
ADD (ST_CADASTRO NUMBER(10) );
ALTER TABLE TB_REPRESENTANTE_INSTITUICAO 
ADD (ID_INSTITUICAO NUMBER(10) );
ALTER TABLE TB_REPRESENTANTE_INSTITUICAO 
ADD (ID_USUARIO NUMBER(10) );
ALTER TABLE TB_REPRESENTANTE_INSTITUICAO
ADD CONSTRAINT FK_REP_IEN FOREIGN KEY
(ID_INSTITUICAO ) REFERENCES TB_INSTITUICAO_ENSINO
(ID_INSTITUICAO ) ENABLE;
ALTER TABLE TB_REPRESENTANTE_INSTITUICAO
ADD CONSTRAINT FK_REP_USU FOREIGN KEY
(ID_USUARIO ) REFERENCES TB_USUARIO
(ID_USUARIO )ENABLE;

ALTER TABLE TB_USUARIO 
ADD (DS_CPF VARCHAR2(255) );

ALTER TABLE TB_SOLICITACAO_SEGUNDA_VIA 
ADD (DS_NOME VARCHAR2(255) );