CREATE TABLE TB_UF (
ID_UF NUMBER(10, 0) NOT NULL, 
SG_UF VARCHAR2(255 CHAR) UNIQUE, 
PRIMARY KEY (ID_UF ) ENABLE);

CREATE TABLE TB_CIDADE (
ID_CIDADE NUMBER(10, 0) NOT NULL, 
NM_CIDADE VARCHAR2(255 CHAR), 
ID_UF NUMBER(10, 0), 
PRIMARY KEY (ID_CIDADE) ENABLE);
 
ALTER TABLE TB_CIDADE ADD CONSTRAINT FK_CIDADE_UF FOREIGN KEY(ID_UF)
REFERENCES TB_UF(ID_UF) ENABLE;


CREATE TABLE TB_ENDERECO (
ID_ENDERECO NUMBER(10, 0) NOT NULL, 
NM_BAIRRO VARCHAR2(255 CHAR), 
NR_CEP VARCHAR2(255 CHAR), 
DS_COMPLEMENTO VARCHAR2(255 CHAR), 
DS_LOGRADOURO VARCHAR2(255 CHAR), 
NR_ENDERECO NUMBER(10, 0), 
ID_CIDADE NUMBER(10, 0),
PRIMARY KEY (ID_ENDERECO) ENABLE);
  
ALTER TABLE TB_ENDERECO ADD CONSTRAINT FK_ENDERECO_CIDADE FOREIGN KEY(ID_CIDADE)
REFERENCES TB_CIDADE(ID_CIDADE) ENABLE;


CREATE TABLE TB_REPRESENTANTE_INSTITUICAO (
ID_REPRESENTANTE NUMBER(10, 0) NOT NULL, 
ST_CARGO NUMBER(10, 0), 
NR_CPF VARCHAR2(255 CHAR) UNIQUE, 
DS_EMAIL VARCHAR2(255 CHAR), 
NM_REPRESENTANTE VARCHAR2(255 CHAR), 
DS_TELEFONE VARCHAR2(255 CHAR), 
PRIMARY KEY (ID_REPRESENTANTE) ENABLE);


CREATE TABLE TB_INSTITUICAO_ENSINO (
  ID_INSTITUICAO NUMBER(10, 0) NOT NULL, 
  NR_CNPJ VARCHAR2(255 CHAR), 
  CD_ESCOLA_SEEDF VARCHAR2(255 CHAR), 
  CD_INEP_EMEC VARCHAR2(255 CHAR), 
  NM_INSTITUICAO VARCHAR2(255 CHAR), 
  ST_PRIVADA NUMBER(10, 0), 
  NM_RAZAO_SOCIAL VARCHAR2(255 CHAR), 
  ST_CADASTRO NUMBER(10, 0), 
  ID_ENDERECO NUMBER(10, 0), 
  ID_REPRESENTANTE NUMBER(10, 0),
  PRIMARY KEY (ID_INSTITUICAO) ENABLE);
  
ALTER TABLE TB_INSTITUICAO_ENSINO
ADD CONSTRAINT FK_INSTITUICAO_REPRESENTANTE FOREIGN KEY(ID_REPRESENTANTE)
REFERENCES TB_REPRESENTANTE_INSTITUICAO(ID_REPRESENTANTE) ENABLE;

ALTER TABLE TB_INSTITUICAO_ENSINO
ADD CONSTRAINT FK_INSTITUICAO_ENDERECO FOREIGN KEY (ID_ENDERECO )
REFERENCES TB_ENDERECO(ID_ENDERECO )ENABLE;


CREATE TABLE TB_CURSO (
ID_CURSO NUMBER(10, 0) NOT NULL, 
CD_EMEC VARCHAR2(255 CHAR), 
DS_CURSO VARCHAR2(255 CHAR), 
DS_NIVEL VARCHAR2(255 CHAR), 
PRIMARY KEY (ID_CURSO) ENABLE);

CREATE TABLE TB_INSTITUICAO_CURSO (
ID_INSTITUICAO_CURSO NUMBER(10, 0) NOT NULL, 
DS_ANO_PERIODO NUMBER(10, 0), 
DT_FIM DATE, 
DT_INICIO DATE, 
DS_TURNO VARCHAR2(255 CHAR), 
ID_CURSO NUMBER(10, 0), 
ID_INSTITUICAO NUMBER(10, 0),
PRIMARY KEY (ID_INSTITUICAO_CURSO) ENABLE);

ALTER TABLE TB_INSTITUICAO_CURSO 
ADD CONSTRAINT FK_INSTITUICAO_CURSO FOREIGN KEY(ID_INSTITUICAO)
REFERENCES TB_INSTITUICAO_ENSINO(ID_INSTITUICAO) ENABLE;

ALTER TABLE TB_INSTITUICAO_CURSO
ADD CONSTRAINT FK_CURSO_INSTITUICAO FOREIGN KEY(ID_CURSO)
REFERENCES TB_CURSO(ID_CURSO) ENABLE;


CREATE TABLE TB_AUTORIZACAO_REPRESENTANTE (
ID_AUTORIZACAO_REPRESENTANTE NUMBER(10, 0) NOT NULL,
NR_CPF VARCHAR2(255 CHAR), 
ID_INSTITUICAO NUMBER(10, 0),
PRIMARY KEY (ID_AUTORIZACAO_REPRESENTANTE) ENABLE );

ALTER TABLE TB_AUTORIZACAO_REPRESENTANTE
ADD CONSTRAINT FK_AUTORIZACAO_INSTITUICAO FOREIGN KEY(ID_INSTITUICAO)
REFERENCES TB_INSTITUICAO_ENSINO(ID_INSTITUICAO) ENABLE;


CREATE TABLE TB_DOCUMENTO_PENDENCIA (
ID_DOCUMENTO NUMBER(10, 0) NOT NULL, 
DS_DOCUMENTO VARCHAR2(255 CHAR), 
NR_DOCUMENTO NUMBER(10, 0), 
PRIMARY KEY (ID_DOCUMENTO) ENABLE);


CREATE TABLE TB_PERFIL (
ID_PERFIL NUMBER(10, 0) NOT NULL,
DS_PERFIL VARCHAR2(255 CHAR),
PRIMARY KEY (ID_PERFIL) ENABLE);



CREATE TABLE TB_USUARIO (
ID_USUARIO NUMBER(10, 0) NOT NULL,
DS_EMAIL VARCHAR2(255 CHAR),
NM_LOGIN VARCHAR2(255 CHAR) UNIQUE,
DS_NOME VARCHAR2(255 CHAR),
ST_RESET_SENHA NUMBER(10, 0),
DS_SENHA VARCHAR2(255 CHAR),
ID_PERFIL NUMBER(10, 0),
PRIMARY KEY(ID_USUARIO) ENABLE );

ALTER TABLE TB_USUARIO
ADD CONSTRAINT FK_USUARIO_PERFIL FOREIGN KEY(ID_PERFIL)
REFERENCES TB_PERFIL(ID_PERFIL) ENABLE;


CREATE TABLE TB_ESTUDANTE (
ID_ESTUDANTE NUMBER(10, 0) NOT NULL,
NR_CPF VARCHAR2(255 CHAR),
DT_NASCIMENTO TIMESTAMP(6),
DS_MATRICULA VARCHAR2(255 CHAR),
NM_ESTUDANTE VARCHAR2(255 CHAR),
NR_PERIODO NUMBER(10, 0),
NM_RESPONSAVELD VARCHAR2(255 CHAR),
ID_INSTITUICAO NUMBER(10, 0),
ID_CURSO NUMBER(10, 0),
ID_ENDERECO NUMBER(10, 0), 
PRIMARY KEY (ID_ESTUDANTE) ENABLE);

ALTER TABLE TB_ESTUDANTE
ADD CONSTRAINT FK_ESTUDANTE_ENDERECO FOREIGN KEY(ID_ENDERECO)
REFERENCES TB_ENDERECO (ID_ENDERECO ) ENABLE;

ALTER TABLE TB_ESTUDANTE
ADD CONSTRAINT FK_ESTUDANTE_CURSO FOREIGN KEY(ID_CURSO)
REFERENCES TB_CURSO(ID_CURSO ) ENABLE;

ALTER TABLE TB_ESTUDANTE
ADD CONSTRAINT FK_ESTUDANTE_INSTITUICAO FOREIGN KEY(ID_INSTITUICAO)
REFERENCES TB_INSTITUICAO_ENSINO(ID_INSTITUICAO) ENABLE;


CREATE TABLE TB_DECLARACAO (
ID_DECLARACAO NUMBER(10, 0) NOT NULL,
DT_DATA_LETIVO_FIM TIMESTAMP(6),
NM_CURSO VARCHAR2(255 CHAR),
DT_AULA_FIM TIMESTAMP(6),
DT_AULA_INICIO TIMESTAMP(6),
DT_LETIVO_INICIO TIMESTAMP(6),
DATANASCIMENTO TIMESTAMP(6),
DS_MATRICULA VARCHAR2(255 CHAR),
CD_INEP_EMEC VARCHAR2(255 CHAR),
NR_PERIODO_SERIE_GRAU NUMBER(10, 0),
NM_RESPONSAVEL VARCHAR2(255 CHAR),
ID_ESTUDANTE NUMBER(10, 0),
ID_INSTITUICAO NUMBER(10, 0),
PRIMARY KEY(ID_DECLARACAO) ENABLE ); 

ALTER TABLE TB_DECLARACAO
ADD CONSTRAINT FK_DECLARACAO_ESTUDANTE FOREIGN KEY(ID_ESTUDANTE)
REFERENCES TB_ESTUDANTE(ID_ESTUDANTE) ENABLE;

ALTER TABLE TB_DECLARACAO
ADD CONSTRAINT FK_DECLARACAO_INSTITUICAO FOREIGN KEY(ID_INSTITUICAO )
REFERENCES TB_INSTITUICAO_ENSINO(ID_INSTITUICAO ) ENABLE;


CREATE TABLE TB_FREQUENCIA (
ID_FREQUENCIA NUMBER(10, 0) NOT NULL,
DT_NASCIMENTO TIMESTAMP(6),
DT_REFERENCIA NUMBER(10, 0),
ST_FREQUENCIA NUMBER(10, 0),
CD_INEP_EMEC VARCHAR2(255 CHAR),
DS_MATRICULA VARCHAR2(255 CHAR),
NM_RESPONSAVEL VARCHAR2(255 CHAR),
ID_ESTUDANTE NUMBER(10, 0),
ID_INSTITUICAO NUMBER(10, 0),
PRIMARY KEY (ID_FREQUENCIA) ENABLE ); 

ALTER TABLE TB_FREQUENCIA
ADD CONSTRAINT FK_FREQUENCIA_ESTUDANTE FOREIGN KEY(ID_ESTUDANTE)
REFERENCES TB_ESTUDANTE(ID_ESTUDANTE) ENABLE;

ALTER TABLE TB_FREQUENCIA
ADD CONSTRAINT FK_FREQUENCIA_INSTITUICAO FOREIGN KEY(ID_INSTITUICAO)
REFERENCES TB_INSTITUICAO_ENSINO(ID_INSTITUICAO ) ENABLE;


CREATE TABLE TB_LOG_BANCO (
ID_LOG_BANCO NUMBER(10, 0) NOT NULL,
DT_ATUALIZACAO TIMESTAMP(6),
ID_LINHA NUMBER(10, 0),
DS_IP VARCHAR2(255 CHAR),
DS_OPERACAO VARCHAR2(255 CHAR),
DS_TABELA VARCHAR2(255 CHAR),
PRIMARY KEY (ID_LOG_BANCO) ENABLE );


CREATE TABLE TB_LOG_VALIDACAO_CADASTRO (
ID_LOG NUMBER(10, 0) NOT NULL,
DT_ATUALIZACAO TIMESTAMP(6),
DS_COMENTARIO VARCHAR2(255 CHAR),
ST_VALIDACAO NUMBER(10, 0),
ID_DOCUMENTO NUMBER(10, 0),
ID_INSTITUICAO NUMBER(10, 0),
ID_USUARIO NUMBER(10, 0),
PRIMARY KEY (ID_LOG) ENABLE ); 

ALTER TABLE TB_LOG_VALIDACAO_CADASTRO
ADD CONSTRAINT FK_LOG_USUARIO FOREIGN KEY(ID_USUARIO )
REFERENCES TB_USUARIO(ID_USUARIO ) ENABLE;

ALTER TABLE TB_LOG_VALIDACAO_CADASTRO
ADD CONSTRAINT FK_LOG_DOCUMENTO FOREIGN KEY(ID_DOCUMENTO )
REFERENCES TB_DOCUMENTO_PENDENCIA (ID_DOCUMENTO) ENABLE;

ALTER TABLE TB_LOG_VALIDACAO_CADASTRO
ADD CONSTRAINT FK_LOG_INSTITUICAO FOREIGN KEY(ID_INSTITUICAO)
REFERENCES TB_INSTITUICAO_ENSINO(ID_INSTITUICAO ) ENABLE;
